"""empty message

Revision ID: 16b9e7873258
Revises: f25dc5b6f0ae
Create Date: 2021-01-24 15:01:55.508252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b9e7873258'
down_revision = 'f25dc5b6f0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardData', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('cardData', sa.Column('imagetype', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardData', 'imagetype')
    op.drop_column('cardData', 'image')
    # ### end Alembic commands ###
