"""empty message

Revision ID: f25dc5b6f0ae
Revises: 7b54dd2ab07b
Create Date: 2021-01-24 14:59:25.014866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f25dc5b6f0ae'
down_revision = '7b54dd2ab07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardData', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardData', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
